### ISSUE TITLE
Graves Override Totems

### ISSUE THREAD

**Issue by edwinzanella** [Skitbet/ActriumGraves#1]
**Describe the bug**
A clear description of what the bug is.

When a totem of undying is held in a player's hand and the player is killed, the totem of undying isn't used and is instead replaced with the gravestone

**To Reproduce**
Steps to reproduce the behavior.

Have a totem of undying in the player's hand. Kill the player such as falling off a cliff. The player will then die instead of the totem being used.

**Expected behavior**
A clear description of what you expected to happen.

The totem is used up rather than the player dying.

**Screenshots / Video**
If applicable, add screenshots or videos to help explain your problem.

**Minecraft Version:**
The version your server is running on. (If you use via version or protocol support please say client version)

Minecraft 1.20.4 Paper Server

**Additional context**

**Comment by Skitbet** [comment]
Will be fixed in 1.2.2
