### ISSUE TITLE
Totems spawn Grave

### ISSUE THREAD

**Issue by Alino001** [Skitbet/ActriumGraves#3]
**Describe the bug**
If you get rescued via a totem, it still spawns a Grave, causing a duplication glitch

**To Reproduce**
Get a totem and try to die.

**Expected behavior**
It shoudnt spawn a Grave.

**Screenshots / Video**
If applicable, add screenshots or videos to help explain your problem.

**Minecraft Version:**
Minecraft Paper 1.20.6 114

**Additional context**
N/A

**Comment by Skitbet** [comment]
Will be fixed in 1.2.3

**Comment by Skitbet** [comment]
Fixed has been published

**Comment by Alino001** [comment]
Thanks :)
