### ISSUE TITLE
grave-under-block overrides existing blocks... including bedrock

### ISSUE THREAD

**Issue by Xetaxheb** [Skitbet/ActriumGraves#4]
**Describe the bug**
grave-under-block overrides existing blocks... including bedrock

**To Reproduce**
die on bedrock

**Expected behavior**
don't replace any existing block besides air or cave_air

**Comment by Skitbet** [comment]
It was meant to replace existing blocks, so ill add a config to disable or reenable it. Also bedrock will be fixed on next update.
